name: app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.5+5

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.5.4
  # Firebase
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.1
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  firebase_storage: ^10.3.10

  carousel_slider: ^4.1.1
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^5.0.2
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.1
  # flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  url_launcher: ^6.1.6
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Din
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Regular.ttf
        - asset: assets/fonts/DINNextLTArabic-Medium.ttf
          weight: 700
